# Generated by Django 3.1.3 on 2020-11-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20201118_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-timestamp']},
        ),
    ]
